An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

try:
    from probml_utils import savefig, latexify, is_latexify_enabled
except ModuleNotFoundError:
    %pip install -qq git+https://github.com/probml/probml-utils.git
    from probml_utils import savefig, latexify, is_latexify_enabled

try:
    import tensorflow_probability.substrates.jax as tfp
except ModuleNotFoundError:
    %pip install -qq tensorflow_probability
    import tensorflow_probability.substrates.jax as tfp
try:
    import jax
    import jax.numpy as jnp
except ModuleNotFoundError:
    %pip install -qq jax
    import jax
    import jax.numpy as np
tfd = tfp.distributions
latexify(width_scale_factor=2, fig_height=1.85)
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3811/2194748959.py in <module>
      3 try:
----> 4     from probml_utils import savefig, latexify, is_latexify_enabled
      5 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'probml_utils'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3811/2194748959.py in <module>
      5 except ModuleNotFoundError:
      6     get_ipython().run_line_magic('pip', 'install -qq git+https://github.com/probml/probml-utils.git')
----> 7     from probml_utils import savefig, latexify, is_latexify_enabled
      8 
      9 try:

ModuleNotFoundError: No module named 'probml_utils'
ModuleNotFoundError: No module named 'probml_utils'
