An error occurred while executing the following cell:
------------------
# Vector Quantization Demo
# Author: Animesh Gupta

# Use racoon face image
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.face.html


import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

try:
    from sklearn import cluster
except ModuleNotFoundError:
    %pip install -qq scikit-learn
    from sklearn import cluster
try:
    import probml_utils as pml
except ModuleNotFoundError:
    %pip install -qq git+https://github.com/probml/probml-utils.git
    import probml_utils as pml

try:  # SciPy >= 0.16 have face in misc
    from scipy.misc import face

    face = face(gray=True)
except ImportError:
    face = sp.face(gray=True)


------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3777/1669414283.py in <module>
     17 try:
---> 18     import probml_utils as pml
     19 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'probml_utils'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3777/1669414283.py in <module>
     19 except ModuleNotFoundError:
     20     get_ipython().run_line_magic('pip', 'install -qq git+https://github.com/probml/probml-utils.git')
---> 21     import probml_utils as pml
     22 
     23 try:  # SciPy >= 0.16 have face in misc

ModuleNotFoundError: No module named 'probml_utils'
ModuleNotFoundError: No module named 'probml_utils'
